import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import { site } from '@/lib/site';

export const metadata: Metadata = { title: 'Gizlilik notu', description: 'Proje formunda paylaştığınız bilgilerin nasıl kullanıldığı hakkında kısa ve açık bir not.', alternates: { canonical: '/gizlilik' }, robots: { index: false, follow: true } };

export default function PrivacyPage() {
  return <article className="container prose-page"><Link href="/" className="back-link"><ArrowLeft size={15} /> Stüdyoya dön</Link><span className="eyebrow">KISA VE AÇIK</span><h1>Gizlilik notumuz.</h1><p className="prose-lead">Projen hakkında konuşmak için paylaştığın bilgileri, o konuşmayı yapabilmek için kullanırız.</p><h2>Hangi bilgiler?</h2><p>Proje formuna yazdığın ihtiyaçlar, seçtiğin özellikler, takvim, adın ve e-posta adresin. Şirket, telefon, bağlantılar ve ek notlar isteğe bağlıdır.</p><h2>Ne için kullanıyoruz?</h2><p>Talebini değerlendirmek, bir kapsam ve teklif hazırlamak ve seninle iletişim kurmak için. Formdan gelen bilgiler otomatik olarak bir pazarlama listesine eklenmez.</p><h2>Nerede tutuluyor?</h2><p>Proje kayıtları stüdyonun sunucusunda saklanır. Bildirim bağlantıları etkinleştirildiğinde, özetin e-posta hizmeti Resend üzerinden iletilebilir ve ekibin özel Slack kanalında paylaşılabilir. Slack’te devam etmeyi seçersen davet sürecinde adın ve e-posta adresin Slack ile paylaşılır.</p><h2>Tarayıcıdaki taslak</h2><p>Formdaki ilerlemen, aynı sekmede devam edebilmen için tarayıcının oturum depolamasında tutulur. Taslak 24 saat sonra yeniden yüklenmez; formu başarıyla gönderdiğinde temizlenir. Tarayıcı sekmesini kapatmak da oturum depolamasını sona erdirir.</p><h2>Saklama süresi</h2><p>Bu formun talep kayıtları 90 günlük saklama süresiyle yönetilir. Süresi dolan kayıtlar bakım işlemi sırasında silinir. Birlikte çalışmaya başladığımızda sözleşme ve işin yürütülmesi için gereken bilgiler ayrıca değerlendirilir.</p><h2>Çerezler ve ölçüm</h2><p>Bu sürümde reklam veya ziyaretçi takip çerezleri kullanılmaz. Yazı tipleri, 3B modeller ve film dosyaları sitenin kendi sunucusundan yüklenir. Formun kötüye kullanımını sınırlamak için kısa süreli, özetlenmiş teknik anahtarlar tutulur.</p><h2>Bir düzeltme veya silme talebin mi var?</h2><p>{site.email ? <><a href={`mailto:${site.email}`}>{site.email}</a> adresinden</> : <><Link href="/baslayalim">İletişim formundan</Link></>} bize ulaşabilirsin. Varsa proje referansını paylaşman kaydını bulmamıza yardımcı olur.</p><p className="prose-date">Son güncelleme: 7 Ekim 2026</p></article>;
}
